spring.application.name=taskManagement
spring.datasource.url=jdbc:postgresql://postgresql:5432/db_task-manager
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=postgres1
spring.jpa.hibernate.ddl-auto=update
otel.propagators=tracecontext
otel.exporter.otlp.endpoint=http://collector:4318
# OpenTelemetry header configuration. If you are using a different collector, you may need to adjust the headers.
otel.exporter.otlp.headers.username=username
otel.exporter.otlp.headers.api-key=Your_Key
otel.resource.attributes.deployment.environment=dev
otel.resource.attributes.service.name=taskmanager
otel.resource.attributes.service.namespace=fairsource