spring.application.name=taskManagement
spring.datasource.url=jdbc:postgresql://postgresql:5432/db_task-manager
spring.datasource.username=postgres
spring.datasource.password=postgres1
spring.jpa.hibernate.ddl-auto=update
otel.propagators=tracecontext
otel.exporter.otlp.endpoint=http://collector:4318
otel.resource.attributes.deployment.environment=dev
otel.resource.attributes.service.name=taskmanager
otel.resource.attributes.service.namespace=fairsource