spring.application.name=taskManagement

spring.datasource.url=jdbc:postgresql://postgresql:5432/db_task-manager
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update